### PR TITLE
Atomics

### PR DESCRIPTION
**Pull request by JDTruj2018**
Making the CUDA `scatter` multi_scatter` and `scatter_gather` kernels perform atomic exchanges by default with no option to disable atomics at the moment. I see about a 30% drop in performance on our H100 for the xrage spatter 9 scatter pattern we have been using for benchmarking.

See https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#atomic-functions, section 7.14.1.3. atomicExch().

Also, see the code example under Section 7.14 for explanation of implementing the atomic operation for doubles

```
#if __CUDA_ARCH__ < 600
__device__ double atomicAdd(double* address, double val)
{
    unsigned long long int* address_as_ull =
                              (unsigned long long int*)address;
    unsigned long long int old = *address_as_ull, assumed;

    do {
        assumed = old;
        old = atomicCAS(address_as_ull, assumed,
                        __double_as_longlong(val +
                               __longlong_as_double(assumed)));

    // Note: uses integer comparison to avoid hang in case of NaN (since NaN != NaN)
    } while (assumed != old);

    return __longlong_as_double(old);
}
#endif
```

See here for a question related to atomic exchanges for doubles: https://forums.developer.nvidia.com/t/atomicexch-double-values/16255

@plavin Do we need atomics for OpenMP? If I remember right, each OpenMP thread has it's own target array to write to?

### CODE REVIEW

**Comment by plavin** [comment]
What is the need for atomics in CUDA? It's because you have patterns that are writing to the same location? 

For OpenMP, there are multiple "dense" buffers. So for Gather, target buffers are replicated, and for Scatter, the source buffers are replicated. This means that if your Scatter pattern writes to the same location multiple times, there will be race conditions. At the time, we decided to just allow those to happen.

**Comment by jyoung3131** [comment]
Hi @JDTruj2018  - Patrick and I were discussing this and we had a few concerns that would be good to at least document before merging:

1) In the related issue we discussed if we needed a flag to use atomics as an option. It seems like it might be good to have a flag since there are potential performance impacts and this PR would cause the OpenMP and CUDA backends to diverge in behavior and performance (ie, if atomics are default only for the CUDA backend)

2) I personally think atomics for the OMP backend would be a "nice to have" but may not be needed to merge this PR. It may be good for the default behavior to be the "performance" variant for backends rather than the "correct/atomic" variant. We can then add atomics for OMP to the future roadmap.

**Comment by JDTruj2018** [comment]
> What is the need for atomics in CUDA? It's because you have patterns that are writing to the same location?

@plavin Yes. Particularly for the xrage patterns we are using with the ATS-5 benchmarking effort, many of those write to the same location.

> For OpenMP, there are multiple "dense" buffers. So for Gather, target buffers are replicated, and for Scatter, the source buffers are replicated. This means that if your Scatter pattern writes to the same location multiple times, there will be race conditions. At the time, we decided to just allow those to happen.

Got it, thanks for clarifying!

**Comment by JDTruj2018** [comment]
> Hi @JDTruj2018 - Patrick and I were discussing this and we had a few concerns that would be good to at least document before merging:
>
> 1. In the related issue we discussed if we needed a flag to use atomics as an option. It seems like it might be good to have a flag since there are potential performance impacts and this PR would cause the OpenMP and CUDA backends to diverge in behavior and performance (ie, if atomics are default only for the CUDA backend)

@jyoung3131 I agree. It may also be nice to compare the performance impact with/without atomics on a single backend.

> 2. I personally think atomics for the OMP backend would be a "nice to have" but may not be needed to merge this PR. It may be good for the default behavior to be the "performance" variant for backends rather than the "correct/atomic" variant. We can then add atomics for OMP to the future roadmap.

That sounds good to me. Do you all have any preference on a specific flag to use to enable to correct/atomic version? 

I'd prefer a partial merge for the CUDA backend that has the current "performance" default behavior and a flag to enable the "correct/atomic" variant for now since it sounds like we need that for a few vendors in the immediate future. We can leave #178 open and then work on a second PR to implement the "correct/atomic" variant for the OpenMP backend to close out the issue since that isn't as critical at the moment.

**Comment by plavin** [comment]
We're probably out of short flags, and I don't think there is any benefit at this point in adding more. Let's just use `--atomic-writes` to enable the feature

**Comment by JDTruj2018** [comment]
Added `--atomic-writes`, which defaults to Off

**Comment by gshipman** [comment]
@plavin @jyoung3131  Can we get a review? Thx!

**Comment by plavin** [comment]
Tests passed on our H100 box

**Review by plavin — APPROVED** [review]

**Pull request merged**
