### PR TITLE
Switches to find_package(OpenMP)

### PR DESCRIPTION
**Pull request by ShadenSmith**
In reference to #2.

NOTE: I did not test with for the ARM configuration. Only GNU/Intel.

### CODE REVIEW

**Comment by avose** [comment]
The Cray compiler uses it's own OpenMP library by default, and if building normally (calling 'cc' -- the compiler wrapper script Cray uses), extra work should not be needed to link OpenMP. That is, one should just use 'cc' and turn OpenMP on with one the supported flags, e.g., -- older CCE: 'cc -homp' (or on by default), cutting edge newer CCE versions may move to a more common 'cc -fopenmp' format. But anyway, I'm just saying that one doesn't typically to anything else special at link time, as the 'cc' wrapper works with the 'modules' system to set all those flags up for the user automatically. I do not know how this interacts with CMake, or if CMake knows anything about how to use Cray's OpenMP.

Now, there may be other design considerations for why you wouldn't want to do the following, but the ./configure/* files seem to be compiler and target specific anyway, with text in their names like "omp", "intel", etc. Why not put the flags needed for OpenMP in there? Then, when a user wants to target a new or a weird system like Cray, they can just put their flags in a new ./configure/* file?

IDK, maybe it's fine, what I see in 'https://github.com/Kitware/CMake/blob/master/Modules/FindOpenMP.cmake' seems to say that will map a Cray compiler to '-h omp' which should still work for most of the older Cray compilers.  We are changing it in a newer release, I think..

**Comment by ShadenSmith** [comment]
I received an email notification of a reply but don't see it here. One question was:

> Now, there may be other design considerations for why you wouldn't want to do the following, but the ./configure/* files seem to be compiler and target specific anyway, with text in their names like "omp", "intel", etc. Why not put the flags needed for OpenMP in there? Then, when a user wants to target a new or a weird system like Cray, they can just put their flags in a new ./configure/* file?

A major reason of using CMake is to avoid that sort of needed configuration customization. There's also a link with `gomp` in the top-level `CMakeLists.txt`, so there are a few edits that need to be made for different architecture/compiler combinations.

**Comment by ShadenSmith** [comment]
Also, I believe that CUDA and OpenCL have equivalent CMake functionality:

https://cmake.org/cmake/help/v3.0/module/FindCUDA.html

https://cmake.org/cmake/help/v3.1/module/FindOpenCL.html

**Comment by jyoung3131** [comment]
I'm going to go ahead and merge this PR and update the issue to specify that we should also use FindCUDA and FindOpenCL instead of manually searching for these includes/libraries.

**Pull request merged**
