### PR TITLE
Spatter Refactor - C++, MPI, Parsing, CMake updates

### PR DESCRIPTION
**Pull request by JDTruj2018**
Re-factoring to C++ to simplify parsing and memory management. The goal is to be as backwards-compatible as possible, from command line flags and behavior, to performance and output.

Currently, the only difference in command line flags is the usage of `-u <--pattern-scatter>` rather than `-h <--pattern-scatter>` to free up the `-h` flag for `--help` and the `-q <--no-print-header>` flag's functionality has been moved to `-v <--verbosity>`. We will have to find a solution for the previous `-v <--vector-len>` flag. Finally, the `-f <--kernel-file>` flag is now used to direct to the JSON file, rather than overloading the `-p` flag.

Changes:
`--help` --> `-h <--help>`
`-h <--pattern-scatter>` --> `-u <--pattern-scatter>`
`-q <--no-print-header>` --> `-v <--verbose>`
`-v <--vector-len>` --> ?
`-f <--kernel-file>` --> `-f <--json-file>`

Are we interested in completing/pursuing this?

Complete:
- [x] Serial, OpenMP, and CUDA Support
- [x] MPI Support
- [x] Building Tests
- [x] Pattern, Pattern Gather, Pattern Scatter, Delta, Delta Gather, Delta Scatter Support
- [x] UNIFORM, MS1, and LAPLACIAN Pattern Support
- [x] Gather, Scatter, Multiscatter, Multigather, Scattergather kernels with single delta Support
- [x] Wrap and Count and single delta support on CPU
- [x] Boundary support (remap)
- [x] Pattern Size support (truncating patterns)
- [x] JSON Parsing Support (nlohmann-json)
- [x] Command Line Parsing Support
- [x] Help and Usage Messages
- [x] CMake Support
- [x] Config Name Support
- [x] Verbosity Levels
- [x] Set number of threads support
- [x] Set number of runs support
- [x] Basic result reporting
- [x] Binary Traces Support 
- [x] Update CUDA Kernels for Delta, Wrap, and Count values (particularly for long patterns). Need a workaround for multi-level kernels, but should be fair for gather, scatter, and gs.
- [x] Verify Performance
- [x] Strong Scaling by Splitting Pattern amongst Ranks
- [x] Atomics for CUDA
- [x] Atomics Options
- [x] Aligned Allocation
- [x] Clean reporting (with MPI) - allreduce for stats
- [x] Catch CUDA Errors (WIP: Shubham, Patrick, Jeff)
- [x] Performance alignment with current Spatter for Gather, Multigather (WIP: Jered/Patrick/Jeff)
- [x] Multiple Target Vectors for OpenMP Backend (WIP: Patrick)
- [x] Passing Tests

To-do:
- [x] Remove unneeded flags/variables (WIP: Jered) - May need to readdress in bugfixes.
- [x] Aggregate, compress, validate (WIP: Connor)
~~- [ ] Multiple Deltas Capability~~
~~- [ ] OpenCL Support~~
~~- [ ] Op Support~~
~~- [ ] PAPI Support~~
~~- [ ] RO_Hilbert, RO_Morton, Strided Support~~
~~- [ ] vector-len Support~~
~~- [ ] Validation moved to #194~~

Future releases:
- Performance alignment with current Spatter for Scatter, Multiscatter, Gather-Scatter (WIP: Jered/Patrick/Jeff) - Progress in #189
- Harmonic mean results (WIP: Jered) - Progress in #196
- Update README with any changes to CLI flags (WIP: Jered) - Progress in #77 
- Update Jupyter notebook and add a test (WIP: Jeff) - Progress in #193 
- Random Seed - testing existing kernel with PGC (WIP: Jered) - Progress in #37 
- Local Work/Block Size for GPU backend - Progress in #195
- Atomics for OpenMP - Progress in #178 

Not Needed:
~~- Old utility files (trace_util.c for example)~~

### CODE REVIEW

**Comment by JDTruj2018** [comment]
@plavin Could you take a look at the CUDA kernels when you get the chance? Particularly the gather, scatter, and gs kernels. My work around to get everything working with `delta`, `count`, and `wrap` without having to do the templating just flattens/expands the pattern prior to copying over to the GPU, so the GPU doesn't have to do any of the `delta` calculations and the entire gather/scatter can be dispatched based on the total number of gather/scatter ops (`pattern.size() * count`) to be performed.

```
    std::vector<size_t> cuda_pattern;
    if (pattern.size() > 0) {
      const size_t pattern_length = pattern.size();
      for (size_t i = 0; i < count; ++i)
        for (size_t j = 0; j < pattern_length; ++j)
          cuda_pattern[i * pattern_length + j] = pattern[j] + delta * i;
    }

    std::vector<size_t> cuda_pattern_gather;
    if (pattern_gather.size() > 0) {
      const size_t pattern_gather_length = pattern_gather.size();
      for (size_t i = 0; i < count; ++i)
        for (size_t j = 0; j < pattern_gather_length; ++j)
          if (kernel.compare("sg") == 0)
            cuda_pattern_gather[i * pattern_gather_length + j] =
                pattern_gather[j] + delta_gather * i;
          else
            // This is cheating - we need an alternative for multi-level on GPU
            cuda_pattern_gather[i * pattern_gather_length + j] =
                pattern[pattern_gather[j]] + delta * i;
    }

    std::vector<size_t> cuda_pattern_scatter;
    if (pattern_scatter.size() > 0) {
      const size_t pattern_scatter_length = pattern_scatter.size();
      for (size_t i = 0; i < count; ++i)
        for (size_t j = 0; j < pattern_scatter_length; ++j)
          if (kernel.compare("sg") == 0)
            cuda_pattern_scatter[i * pattern_scatter_length + j] =
                pattern_scatter[j] + delta_scatter * i;
          else
            // This is cheating - we need an alternative for multi-level on GPU
            cuda_pattern_scatter[i * pattern_scatter_length + j] =
                pattern[pattern_scatter[j]] + delta * i;
    }

    cudaMalloc((void **)&dev_pattern, sizeof(size_t) * cuda_pattern.size());
    cudaMalloc((void **)&dev_pattern_gather,
        sizeof(size_t) * cuda_pattern_gather.size());
    cudaMalloc((void **)&dev_pattern_scatter,
        sizeof(size_t) * cuda_pattern_scatter.size());

    cudaMalloc((void **)&dev_sparse, sizeof(double) * sparse.size());
    cudaMalloc(
        (void **)&dev_sparse_gather, sizeof(double) * sparse_gather.size());
    cudaMalloc(
        (void **)&dev_sparse_scatter, sizeof(double) * sparse_scatter.size());
    cudaMalloc((void **)&dev_dense, sizeof(double) * dense.size());

    cudaMemcpy(dev_pattern, cuda_pattern.data(),
        sizeof(size_t) * cuda_pattern.size(), cudaMemcpyHostToDevice);
    cudaMemcpy(dev_pattern_gather, cuda_pattern_gather.data(),
        sizeof(size_t) * cuda_pattern_gather.size(), cudaMemcpyHostToDevice);
    cudaMemcpy(dev_pattern_scatter, cuda_pattern_scatter.data(),
        sizeof(size_t) * cuda_pattern_scatter.size(), cudaMemcpyHostToDevice);

    cudaMemcpy(dev_sparse, sparse.data(), sizeof(double) * sparse.size(),
        cudaMemcpyHostToDevice);
    cudaMemcpy(dev_sparse_gather, sparse_gather.data(),
        sizeof(double) * sparse_gather.size(), cudaMemcpyHostToDevice);
    cudaMemcpy(dev_sparse_scatter, sparse_scatter.data(),
        sizeof(double) * sparse_scatter.size(), cudaMemcpyHostToDevice);
    cudaMemcpy(dev_dense, dense.data(), sizeof(double) * dense.size(),
        cudaMemcpyHostToDevice);
```

```
#include <cuda.h>
#include <cuda_runtime.h>

__global__ void cuda_gather(const size_t *pattern, const double *sparse,
    double *dense, const int gsops, const int dense_length) {
  int i = blockDim.x * blockIdx.x + threadIdx.x;

  if (i < gsops)
    dense[i % dense_length] = sparse[pattern[i]];
}

__global__ void cuda_scatter(const size_t *pattern, double *sparse,
    const double *dense, const int gsops, const int dense_length) {
  int i = blockDim.x * blockIdx.x + threadIdx.x;

  if (i < gsops)
    sparse[pattern[i]] = dense[i % dense_length];
}

__global__ void cuda_scatter_gather(const size_t *pattern_scatter,
    double *sparse_scatter, const size_t *pattern_gather,
    const double *sparse_gather, const int gsops) {
  int i = blockDim.x * blockIdx.x + threadIdx.x;

  if (i < gsops)
    sparse_scatter[pattern_scatter[i]] = sparse_gather[pattern_gather[i]];
}

__global__ void cuda_multi_gather(const size_t *pattern,
    const size_t *pattern_gather, const double *sparse, double *dense,
    const int gsops, const int dense_length) {
  int i = blockDim.x * blockIdx.x + threadIdx.x;

  if (i < gsops)
    dense[i % dense_length] = sparse[pattern_gather[i]];
}

__global__ void cuda_multi_scatter(const size_t *pattern,
    const size_t *pattern_scatter, double *sparse, const double *dense,
    const int gsops, const int dense_length) {
  int i = blockDim.x * blockIdx.x + threadIdx.x;

  if (i < gsops)
    sparse[pattern_scatter[i]] = dense[i % dense_length];
}

void cuda_gather_wrapper(const size_t *pattern, const double *sparse,
    double *dense, const int pattern_length, const size_t count,
    const size_t wrap) {
  int gsops = (int)((int)pattern_length * (int)count);
  int dense_length = pattern_length * (int)wrap;

  int threads_per_block = 256;
  int blocks_per_grid = (gsops + threads_per_block - 1) / threads_per_block;
  cuda_gather<<<blocks_per_grid, threads_per_block>>>(
      pattern, sparse, dense, gsops, dense_length);
}

void cuda_scatter_wrapper(const size_t *pattern, double *sparse,
    const double *dense, const int pattern_length, const size_t count,
    const size_t wrap) {
  int gsops = (int)((int)pattern_length * (int)count);
  int dense_length = pattern_length * (int)wrap;

  int threads_per_block = 256;
  int blocks_per_grid = (gsops + threads_per_block - 1) / threads_per_block;
  cuda_scatter<<<blocks_per_grid, threads_per_block>>>(
      pattern, sparse, dense, gsops, dense_length);
}

void cuda_scatter_gather_wrapper(const size_t *pattern_scatter,
    double *sparse_scatter, const size_t *pattern_gather,
    const double *sparse_gather, const int pattern_length, const size_t count,
    const size_t wrap) {
  int gsops = (int)((int)pattern_length * (int)count);

  int threads_per_block = 256;
  int blocks_per_grid = (gsops + threads_per_block - 1) / threads_per_block;
  cuda_scatter_gather<<<blocks_per_grid, threads_per_block>>>(
      pattern_scatter, sparse_scatter, pattern_gather, sparse_gather, gsops);
}

void cuda_multi_gather_wrapper(const size_t *pattern,
    const size_t *pattern_gather, const double *sparse, double *dense,
    const int pattern_length, const size_t count, const size_t wrap) {
  int gsops = (int)((int)pattern_length * (int)count);
  int dense_length = pattern_length * (int)wrap;

  int threads_per_block = 256;
  int blocks_per_grid = (gsops + threads_per_block - 1) / threads_per_block;
  cuda_multi_gather<<<blocks_per_grid, threads_per_block>>>(
      pattern, pattern_gather, sparse, dense, gsops, dense_length);
}

void cuda_multi_scatter_wrapper(const size_t *pattern,
    const size_t *pattern_scatter, double *sparse, const double *dense,
    const int pattern_length, const size_t count, const size_t wrap) {
  int gsops = (int)((int)pattern_length * (int)count);
  int dense_length = pattern_length * (int)wrap;

  int threads_per_block = 256;
  int blocks_per_grid = (gsops + threads_per_block - 1) / threads_per_block;
  cuda_multi_scatter<<<blocks_per_grid, threads_per_block>>>(
      pattern, pattern_scatter, sparse, dense, gsops, dense_length);
}
```

This doesn't work for the multi-level kernels since the CPU would actually have to do the first level of indirection, but I'm not too concerned about that right now since we just need the single-level GPU kernels to work well with long patterns. Technically, we don't have any `delta` values in our patterns, but I'd like to keep that ability for other folks of course. If we didn't have to worry about `delta`, `count`, or `wrap`, the previous solution would have worked without the extra step of flattening/expanding the pattern array.

**Comment by JDTruj2018** [comment]
Some early performance numbers on Haswell

image

**Comment by JDTruj2018** [comment]
GPU Performance still needs some work (this is a V100)

Original:
```
../../spatter/build_cuda_workflow/spatter -b cuda -pUNIFORM:1024:1 -l 1048576 -k gather -q2
config  bytes        time(s)      bw(MB/s)    
0       8589934592   0.007443     1154079.646614

Min         25%          Med          75%          Max         
1.15408e+06  1.15408e+06  1.15408e+06  1.15408e+06  1.15408e+06 
H.Mean       H.StdErr    
```

New:
```
./src/spatter-driver -pUNIFORM:1024:1 -l 1048576 -k gather -b cuda -v 0
config         bytes          time(s)        bw(MB/s)       
0              8589934592     0.0127528      673570 
```

**Comment by JDTruj2018** [comment]
I'd been installing `nlohmann_json` with Spack, but can try to get CMake to install it automatically if that would be easier.

**Comment by plavin** [comment]
Yeah, I think a CMake approach would be better. I was able to compile it by adding the following lines to the top-level CMakeLists.txt, although I'm sure that is the right place to add it

```
if (CMAKE_VERSION VERSION_GREATER_EQUAL "3.24.0")
    cmake_policy(SET CMP0135 NEW)
endif()
FetchContent_Declare(nlohmann_json URL https://github.com/nlohmann/json/releases/download/v3.11.2/json.tar.xz OVERRIDE_FIND_PACKAGE)
FetchContent_MakeAvailable(nlohmann_json)
```

I was also missing `#include <vector>` from `Configuration.hh`

I'm working to check out some performance numbers on the H100 now. I only get about 1.4TB/s (out of 2TB/s) for Gather

**Comment by JDTruj2018** [comment]
I am getting 2TB/s on our H100 nodes

```
./src/spatter-driver -p UNIFORM:8192:1 -l 1024 -d 8 -b cuda

Running Spatter version 1.1
Compiler: GNU ver. 9.4.0
Backend: CUDA
Aggregate Results? NO
Number of Devices: 1
Device Name: NVIDIA H100 PCIe
Memory Clock Rage (KHz): 1593000
Memory Bus Width (bits): 5120
Peak Memory Bandwidth (GB/s): 2039.04

config         bytes          time(s)        bw(MB/s)       
0              67108864       3.29536e-05    2.03647e+06    
```

This was my CMake command

```
mkdir build
cmake -DCMAKE_BUILD_TYPE=Release -DUSE_CUDA=ON ..
make
```

**Comment by plavin** [comment]
Guess I was running the old executable. I'm getting 2TB/s now. 

Regarding the features you asked about, here are my thoughts on whether we need each or not: 

- Aligned Allocation
  - Yes. This is important for getting high performance on CPU
- Old utility files (trace_util.c for example)
  - No
- Aggregate, compress, validate
  - Aggregate can be dropped and made the default behavior. If multiple runs are requested for a pattern we can just print the max bandwidth
  - I think we want to keep compress, especially given some of the patterns we have seen from branson and quicksilver.
  - Validate is tricky. It's probably ok to leave that out for now and we can come up with a better solution in the future.
- Multiple Deltas Capability
  - No
- OpenCL Support
  - No
- Op Support
  - No, this was never added
- PAPI Support
  - No. This hasn't been used in a long time
- RO_Hilbert, RO_Morton, Strided Support
  - No. This hasn't been used in a while and didn't provide any performance benefits
- vector-len Support
  - I think we should just let users worry about that themselves with the pattern size they use. Fine to drop.

**Comment by JDTruj2018** [comment]
Great, thank you! I'll see if I can get most of this working and tested on this PR.

I'll put together a separate (smaller) PR that only incorporates the GPU long pattern work into Spatter and we can iterate on that as well. If you have other thoughts on the cool CUDA JIT work you had been doing as well, let me know!

**Comment by plavin** [comment]
@JDTruj2018 
Would it be possible to build Spatter as a shared library instead of (or in addition to) an interface library? This would potentially enable us to use the parser in other code (such as SST).

**Comment by radelja** [comment]
@JDTruj2018 I've encountered a couple issues with this refactor:

- Truncating patterns with the -j option works, but not when I specify pattern-size in a JSON file
- I'm able to run a GS pattern with the -g, -u, and -k options, but not when I use pattern-gather, pattern-scatter, and kernel in a JSON file

**Comment by JDTruj2018** [comment]
> @JDTruj2018 I've encountered a couple issues with this refactor:
> 
> * Truncating patterns with the -j option works, but not when I specify pattern-size in a JSON file
> * I'm able to run a GS pattern with the -g, -u, and -k options, but not when I use pattern-gather, pattern-scatter, and kernel in a JSON file

Hi Connor @radelja,

Could you provide me a short example JSON file and the command you are using the run Spatter?

I think this gets at a larger discussion about whether or not it makes sense for command line args to overrule parameters set in the JSON file. 

It also gets at a discussion about per pattern options and per run options, where it makes sense to be able to set per run options on the command line and the command line only (such as the backend), and per pattern options come directly from the JSON and cannot be overruled from the command line (i.e. they are ignored if given a JSON).

**Comment by radelja** [comment]
Certainly, the first example uses [cpu-stream.json](https://github.com/JDTruj2018/spatter/blob/refactor/standard-suite/basic-tests/cpu-stream.json) from the refactor branch and the second example uses [cpu-stream.json](https://github.com/hpcgarage/spatter/blob/main/standard-suite/basic-tests/cpu-stream.json) from the main branch.

Example 1: ./build_serial_gnu/src/spatter-driver -fstandard-suite/basic-tests/cpu-stream.json

This JSON file has four configs, where the first two specify the pattern-size argument. In this example, the pattern for the first two configs should be truncated. However, the number of bytes moved for these two configs does not reflect this; 1,073,741,824 bytes moved instead of 536,870,912 bytes.

Example 2: ./build_serial_gnu/src/spatter-driver ../../hpcgarage/spatter/standard-suite/basic-tests/cpu-stream.json

The third config for this JSON file specifies a GS kernel, it provides a gather pattern with the pattern-gather argument and a scatter pattern with pattern-scatter. Since no pattern is provided using the pattern argument, the config does not run.

**Comment by radelja** [comment]
I discussed adding support for generating position-independent code with Jeff and Patrick this past Thursday. From what I recall, using separate CMake targets to compile the library with position-independent code and the executable without position-independent code was suggested. Currently, a shared or static library with position-independent code can be compiled with CMake using BUILD_SHARED_LIBS or CMAKE_POSITION_INDEPENDENT_CODE. To prevent the executable compiled as a position-independent executable, the -no-pie link option can be specified. Compiling both a static library without position-independent code for the executable, and a shared library for external applications could also be considered.

**Comment by plavin** [comment]
I have worked on the OpenMP backend. Right now it looks like I'm getting junk data out of the gather kernel.

https://github.com/plavin/spatter/tree/refactor-new

TODOs
- [ ] Fix Gather kernel
- [ ] Write other kernels
- [ ] Add atomic write support

**Comment by plavin** [comment]
- [ ] We need to change ConfigurationBase::report() to report the minimum time, not the mean, to match the original Spatter behavior.

**Comment by radelja** [comment]
> Certainly, the first example uses [cpu-stream.json](https://github.com/JDTruj2018/spatter/blob/32650aa866b71599303f19f9ab0244a1fc472466/standard-suite/basic-tests/cpu-stream.json) from the refactor branch and the second example uses [cpu-stream.json](https://github.com/hpcgarage/spatter/blob/main/standard-suite/basic-tests/cpu-stream.json) from the main branch.
> 
> Example 1: ./build_serial_gnu/src/spatter-driver -fstandard-suite/basic-tests/cpu-stream.json
> 
> This JSON file has four configs, where the first two specify the pattern-size argument. In this example, the pattern for the first two configs should be truncated. However, the number of bytes moved for these two configs does not reflect this; 1,073,741,824 bytes moved instead of 536,870,912 bytes.

I have identified what causes the issue I described above, where patterns would not get truncated when specifying the pattern-size argument in JSON files. The patterns are truncated, using the pattern-size argument specified through the `-j` or `--pattern-size` flags, before the JSON files are parsed:

https://github.com/JDTruj2018/spatter/blob/428833c00daa38ca8440d7e4b57233446cfd601e/src/Spatter/Input.hh#L492-L527

**Comment by radelja** [comment]
As #183 mentions, Spatter uses the default value of 8 when a negative delta is specified via the command-line. The handling of negative delta values in JSON files is now consistent with the current Spatter version, but this is still an issue when specifying a negative delta with the `-d` or `--delta` flags. Looking at how deltas are parsed when specified via the command-line reveals **another issue**: if a negative delta is specified, the [read_ul_arg](https://github.com/JDTruj2018/spatter/blob/4dca591e0538ddd83c4a78fd65b854155e728f0e/src/Spatter/Input.hh#L198-L206) function will attempt to set a size_t type using this negative value.

**Review by jyoung3131 — APPROVED** [review]
We've reviewed the codebase, tested multiple variations, and reviewed all the outstanding issues. While there are likely some small bugfixes and additional testing, we've pulled these out into smaller issues that can be addressed, as needed.

**Pull request merged**
