### PR TITLE
Concurrent Gather/Scatter

### LINKED ISSUE #78: Concurrent gather/scatter
We'd like to support mixing concurrent gather/scatter operations within a pattern. It seems that the easiest way to do this is to use two index arrays - one for scatter and one for gather and base the index access on the type of operation/kernel that is called.

### PR DESCRIPTION
**Pull request by JDTruj2018**
Serial: Complete
OpenMP: Complete
CUDA: Complete

closes #78 
closes #86

### CODE REVIEW

**Comment by plavin** [comment]
This segfaults on `./spatter -p:UNIFORM:8:1`. This was a bug I think we fixed on the master branch, but even when I rebase this PR on master I get the bug. 

When I compile with ASAN, I get the following:

```
=85598==ERROR: AddressSanitizer: stack-overflow on address 0x00016d3b1100 (pc 0x0001020da50c bp 0x00016d781e90 sp 0x00016d3b1040 T0)
    #0 0x1020da50c in parse_runs parse-args.c:350
    #1 0x1020de614 in parse_args parse-args.c:340
    #2 0x1020d1160 in main main.c:288
    #3 0x102ad9088 in start+0x204 (dyld:arm64e+0x5088)
```

**Comment by JDTruj2018** [comment]
@plavin 

Latest commit should fix the segfault on `./spatter -p:UNIFORM:8:1`
Was an error of not including parenthesis when dereferencing the a pointer to an array

Have also included an initial CUDA concurrent back-end. I will forego the OpenCL back-end for now unless we deem it necessary.

I will do more testing later this week. Let me know if you run into any more issues/bugs.

**Comment by plavin** [comment]
Thanks for finding that bug. 

Could you give an example of how to run the new kernel? I tried `./spatter -kSG -pUNIFORM:8:1` but got `Error: Unsupported kernel`. 

If you run `make test`, tests 10 and 12 fail. But 10 fails on the master branch as well. Could you take a look at why test 12 is segfaulting?

**Comment by plavin** [comment]
Actually, I'm getting some strange behavior in the tests. Now 9-12 fail for me on master, and only 9,10,12 fail on your branch. I'll look into it.

**Comment by plavin** [comment]
I updated master to fix issues with testing. If it's not too much trouble, please rebase this branch on master and force push so that the new workflow will run. (The new workflow runs `make test`).

**Comment by JDTruj2018** [comment]
An example run is: `./spatter -k SG -t 0,1,2,3 -u 0,1,2,3`

Currently, we have to specify both the scatter pattern and the gather pattern separately. If we want the ability to use built-in patterns, such as UNIFORM, for both the scatter and gather, I can work on adding that.

I'll check out the tests and rebase later today

**Comment by JDTruj2018** [comment]
Fixed the UNIFORM issue. Tested on the following:
```
./spatter -kSG -gUNIFORM:8:1 -hUNIFORM:8:1
./spatter -kSG -gUNIFORM:8:1 -h0,1,2,3,4,5,6,10
./spatter -kSG -gLAPLACIAN:2:2:2 -h0,1,2,3,4,5,6,7,8
./spatter -kSG -gLAPLACIAN:2:2:2 -hUNIFORM:9:1
./spatter -kSG -gHYDRO:2 -hHYDRO:2
./spatter -kSG -gHYDRO:2 -hXKP:2
./spatter -kSG -gHYDRO:2 -hMS1:73:1,2:1,2
```

**Comment by plavin** [comment]
I added a couple tests and renamed SG to GS. We used GS in the paper for a couple reasons: since we normally say read/write, it makes sense to say gather/scatter as those are the analogous operations. And since the gather happens first in the kernel, I think it makes sense to name it GS. I should have mentioned that earlier. 

Anyways, it looks good to me. I think we'll tune the output a bit so that we're not always printing pattern, pattern_gather, and pattern_scatter. But that can wait. I'm excited to have this back in Spatter, and I like that we can use any of the patterns for -h and -g.

**Pull request merged**
